apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - runtime-sa.yaml
  - backend.yaml
  - frontend.yaml
  - gateway/nginx-proxy.yaml
  - gateway/gateway.yaml
  - gateway/httproute.yaml
